name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t bot_image:latest .

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Docker Image to Server
        run: |
          docker save bot_image:latest | bzip2 | ssh -v -o StrictHostKeyChecking=no \
          -o IdentitiesOnly=yes -p ${{ secrets.SERVER_PORT }} \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'bunzip2 | docker load'

      - name: Deploy Application
        run: |
          ssh -v -o StrictHostKeyChecking=no -o IdentitiesOnly=yes \
          -p ${{ secrets.SERVER_PORT }} \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            mkdir -p /home/my_bot
            cd /home/my_bot
            if [ "$(docker ps -q -f name=bot_name)" ]; then
              docker stop bot_name
              docker rm bot_name
            fi
            docker run -it -d \
              --env-file .env \
              --restart=unless-stopped \
              --name bot_name \
              bot_image:latest
          EOF
